export type PreparedImage={dataBase64:string;contentType:'image/jpeg';fileName:string;sourceBytes:number;outputBytes:number;width:number;height:number};
const MAX_INPUT_BYTES=20*1024*1024;const TARGET_BASE64=2600000;
function dataBase64(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const value=String(reader.result||'');resolve(value.includes(',')?value.split(',')[1]:value);};reader.onerror=()=>reject(new Error('The image could not be read.'));reader.readAsDataURL(blob);});}
type DecodedImage={source:CanvasImageSource;width:number;height:number;cleanup:()=>void};function loadHtmlImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('decode_failed'));image.src=src;});}async function loadFileImage(file:File):Promise<DecodedImage>{if(typeof createImageBitmap==='function'){try{const bitmap=await createImageBitmap(file);if(bitmap.width>0&&bitmap.height>0)return{source:bitmap,width:bitmap.width,height:bitmap.height,cleanup:()=>bitmap.close()};}catch{}}let objectUrl='';try{objectUrl=URL.createObjectURL(file);const image=await loadHtmlImage(objectUrl);URL.revokeObjectURL(objectUrl);return{source:image,width:image.naturalWidth,height:image.naturalHeight,cleanup:()=>{}};}catch{if(objectUrl)URL.revokeObjectURL(objectUrl);}try{const encoded=await dataBase64(file);const image=await loadHtmlImage(`data:${file.type||'image/jpeg'};base64,${encoded}`);return{source:image,width:image.naturalWidth,height:image.naturalHeight,cleanup:()=>{}};}catch{}throw new Error('This browser could not decode the selected photograph. Open it in Gallery, save or export a fresh JPG copy, then upload that copy.');}
function canvasBlob(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('The image could not be prepared.')),'image/jpeg',quality));}
export async function preparePortfolioImage(file:File):Promise<PreparedImage>{const extension=file.name.split('.').pop()?.toLowerCase()||'';if(!file.type.startsWith('image/')&&!['jpg','jpeg','png','webp'].includes(extension))throw new Error('Choose a JPG, PNG or WebP photograph.');if(file.size>MAX_INPUT_BYTES)throw new Error('This photograph is too large. Choose an image under 20 MB.');const image=await loadFileImage(file);try{let maxDimension=2200;let quality=.86;for(let attempt=0;attempt<8;attempt+=1){const longest=Math.max(image.width,image.height);const scale=Math.min(1,maxDimension/longest);const width=Math.max(1,Math.round(image.width*scale));const height=Math.max(1,Math.round(image.height*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image processing is unavailable in this browser.');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,width,height);ctx.drawImage(image.source,0,0,width,height);const blob=await canvasBlob(canvas,quality);const encoded=await dataBase64(blob);if(encoded.length<=TARGET_BASE64)return{dataBase64:encoded,contentType:'image/jpeg',fileName:file.name.replace(/\.[^.]+$/,'')+'.jpg',sourceBytes:file.size,outputBytes:blob.size,width,height};if(quality>.66)quality-=.07;else{maxDimension=Math.max(1200,Math.floor(maxDimension*.82));quality=.78;}}throw new Error('This photograph could not be reduced to a safe upload size. Try a smaller image.');}finally{image.cleanup();}}
export function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/(1024*1024)).toFixed(1)} MB`;}
export function apiError(err:unknown,fallback:string){const value=err as {response?:{data?:{error?:string;message?:string}};message?:string};const message=value.response?.data?.error||value.response?.data?.message||value.message||'';if(message.includes('AppDatabaseQuotaExceeded'))return 'Studio Ops is temporarily rate-limited. Wait about a minute, then try again. Your existing records are safe.';if(message&&message.length<240&&!/401|403|unauthorized|forbidden/i.test(message))return message;return fallback;}
export function pageUrl(path:string,nextToken?:string){return nextToken?`${path}?nextToken=${encodeURIComponent(nextToken)}&limit=25`:`${path}?limit=25`;}
